; This file was automatically generated by ScriptHubImporter.py
<<<<<<< Updated upstream
global g_ImportsGameVersion64 := 517
=======
global g_ImportsGameVersion64 := 515
>>>>>>> Stashed changes
global g_ImportsGameVersionPostFix64 := ""